In [1]:
import xarray as xr
import netCDF4
import numpy as np
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature
import pandas as pd
import numpy as np
import xesmf as xe


In [2]:
#Abro los 7 datasets
clt_model1 = xr.open_dataset(r"..\modelos\clt\clt_Amon_ACCESS-CM2_historical_r1i1p1f1_gn_185001-201412.nc")
clt_model2 = xr.open_dataset(r"..\modelos\clt\clt_Amon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_185001-201412.nc")
clt_model3 = xr.open_dataset(r"..\modelos\clt\clt_Amon_CESM2-WACCM_historical_r1i1p1f1_gn_185001-201412.nc")
clt_model4 = xr.open_dataset(r"..\modelos\clt\clt_Amon_CMCC-CM2-SR5_historical_r1i1p1f1_gn_185001-201412.nc")
clt_model5 = xr.open_dataset(r"..\modelos\clt\clt_Amon_FIO-ESM-2-0_historical_r1i1p1f1_gn_185001-201412.nc")
clt_model6 = xr.open_dataset(r"..\modelos\clt\clt_Amon_MRI-ESM2-0_historical_r1i1p1f1_gn_185001-201412.nc")
clt_model7 = xr.open_dataset(r"..\modelos\clt\clt_Amon_TaiESM1_historical_r1i1p1f1_gn_185001-201412.nc")

c:\Users\clara\miniconda3\envs\solarProject\Lib\site-packages\xarray\conventions.py:204: SerializationWarning: variable 'clt' has multiple fill values {np.float32(1e+20), np.float64(1e+20)} defined, decoding all values to NaN.
  var = coder.decode(var, name=name)


In [3]:
pr_model1 = xr.open_dataset(r"..\modelos\pr\pr_Amon_ACCESS-CM2_historical_r1i1p1f1_gn_185001-201412.nc")
pr_model2 = xr.open_dataset(r"..\modelos\pr\pr_Amon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_185001-201412.nc")
pr_model3 = xr.open_dataset(r"..\modelos/pr/pr_Amon_CESM2-WACCM_historical_r1i1p1f1_gn_185001-201412.nc")
pr_model4 = xr.open_dataset(r"..\modelos\pr\pr_Amon_CMCC-CM2-SR5_historical_r1i1p1f1_gn_185001-201412.nc")
pr_model5 = xr.open_dataset(r"..\modelos\pr\pr_Amon_FIO-ESM-2-0_historical_r1i1p1f1_gn_185001-201412.nc")
pr_model6 = xr.open_dataset(r"..\modelos\pr\pr_Amon_MRI-ESM2-0_historical_r1i1p1f1_gn_185001-201412.nc")
pr_model7 = xr.open_dataset(r"..\modelos\pr\pr_Amon_TaiESM1_historical_r1i1p1f1_gn_185001-201412.nc")

c:\Users\clara\miniconda3\envs\solarProject\Lib\site-packages\xarray\conventions.py:204: SerializationWarning: variable 'pr' has multiple fill values {np.float32(1e+20), np.float64(1e+20)} defined, decoding all values to NaN.
  var = coder.decode(var, name=name)


In [9]:
print(clt_model1['clt'])

<xarray.DataArray 'clt' (time: 1980, lat: 144, lon: 192)> Size: 219MB
array([[[90.16113 , 90.6189  , ..., 89.95972 , 89.660645],
        [92.27905 , 91.40015 , ..., 91.94336 , 92.13867 ],
        ...,
        [98.42529 , 98.21777 , ..., 98.55957 , 98.376465],
        [97.58301 , 97.58911 , ..., 97.86377 , 97.79663 ]],

       [[87.457275, 88.10425 , ..., 88.25073 , 88.323975],
        [74.38965 , 74.279785, ..., 73.17505 , 73.04077 ],
        ...,
        [99.31641 , 99.33472 , ..., 99.20654 , 99.18213 ],
        [98.358154, 98.44971 , ..., 98.132324, 98.42529 ]],

       ...,

       [[93.20679 , 93.41431 , ..., 93.85376 , 93.829346],
        [93.86597 , 93.7561  , ..., 93.566895, 93.61572 ],
        ...,
        [97.76001 , 97.857666, ..., 97.63794 , 97.58911 ],
        [98.12622 , 98.29712 , ..., 98.03467 , 98.36426 ]],

       [[85.30884 , 84.74121 , ..., 84.765625, 85.198975],
        [87.92114 , 87.18262 , ..., 87.68921 , 87.30469 ],
        ...,
        [93.07251 , 93.7439  , ..

In [ ]:
clt_regridder1 = xe.Regridder(clt_model1['clt'], clt_model3['clt'], 'bilinear', extrap_method='nearest_s2d')
clt_regridder2 = xe.Regridder(clt_model2['clt'], clt_model3['clt'], 'bilinear', extrap_method='nearest_s2d')
clt_regridder3 = xe.Regridder(clt_model6['clt'], clt_model3['clt'], 'bilinear', extrap_method='nearest_s2d')

clt_model1rg = clt_regridder1(clt_model1['clt'])
clt_model2rg = clt_regridder2(clt_model2['clt'])
clt_model6rg = clt_regridder3(clt_model6['clt'])

In [11]:
clt_model1rg

<xarray.DataArray (time: 1980, lat: 192, lon: 288)> Size: 438MB
array([[[ 92.08984 ,  92.08984 ,  92.08984 , ...,  92.08984 ,
          92.08984 ,  92.08984 ],
        [ 90.16113 ,  90.71877 ,  90.797615, ...,  90.343506,
          90.43462 ,  90.31896 ],
        [ 92.13867 ,  92.122665,  91.54311 , ...,  91.8848  ,
          91.95943 ,  92.0892  ],
        ...,
        [ 98.376465,  98.3929  ,  98.25576 , ...,  98.56112 ,
          98.52989 ,  98.40789 ],
        [ 97.58301 ,  97.78891 ,  97.75681 , ...,  97.98361 ,
          98.0244  ,  97.96001 ],
        [ 95.8313  ,  95.8313  ,  95.8313  , ...,  95.8313  ,
          95.8313  ,  95.8313  ]],

       [[ 93.85986 ,  93.85986 ,  93.85986 , ...,  93.85986 ,
          93.85986 ,  93.85986 ],
        [ 87.457275,  84.21403 ,  84.51717 , ...,  84.144615,
          84.42508 ,  84.43877 ],
        [ 73.04077 ,  74.3455  ,  74.27838 , ...,  73.25699 ,
          73.12719 ,  73.0439  ],
...
        [ 97.58911 ,  97.76902 ,  97.83558 , ...,  97.56226 ,
          97.62424 ,  97.59217 ],
        [ 98.12622 ,  98.05859 ,  98.16012 , ...,  97.98435 ,
          97.97282 ,  98.12846 ],
        [ 97.86377 ,  97.86377 ,  97.86377 , ...,  97.86377 ,
          97.86377 ,  97.86377 ]],

       [[ 85.2478  ,  85.2478  ,  85.2478  , ...,  85.2478  ,
          85.2478  ,  85.2478  ],
        [ 85.30884 ,  85.87049 ,  85.46315 , ...,  85.73601 ,
          85.54579 ,  85.6962  ],
        [ 87.30469 ,  87.77076 ,  87.28404 , ...,  88.078896,
          87.58661 ,  87.33572 ],
        ...,
        [ 93.65845 ,  93.17506 ,  93.61942 , ...,  93.464645,
          93.61676 ,  93.6393  ],
        [ 97.38159 ,  96.30644 ,  96.3837  , ...,  96.53952 ,
          96.64447 ,  96.3866  ],
        [ 97.19238 ,  97.19238 ,  97.19238 , ...,  97.19238 ,
          97.19238 ,  97.19238 ]]], shape=(1980, 192, 288), dtype=float32)
Coordinates:
  * time     (time) datetime64[ns] 16kB 1850-01-16T12:00:00 ... 2014-12-16T12...
  * lat      (lat) float64 2kB -90.0 -89.06 -88.12 -87.17 ... 88.12 89.06 90.0
  * lon      (lon) float64 2kB 0.0 1.25 2.5 3.75 5.0 ... 355.0 356.2 357.5 358.8
Attributes:
    regrid_method:  bilinear

In [14]:
pr_regridder1 = xe.Regridder(pr_model1['pr'], pr_model3['pr'], 'bilinear', extrap_method='nearest_s2d')
pr_regridder2 = xe.Regridder(pr_model2['pr'], pr_model3['pr'], 'bilinear', extrap_method='nearest_s2d')
pr_regridder3 = xe.Regridder(pr_model6['pr'], pr_model3['pr'], 'bilinear', extrap_method='nearest_s2d')

pr_model1rg = pr_regridder1(pr_model1['pr'])
pr_model2rg = pr_regridder2(pr_model2['pr'])
pr_model6rg = pr_regridder3(pr_model6['pr'])

In [15]:
pr_model1rg

<xarray.DataArray (time: 1980, lat: 192, lon: 288)> Size: 438MB
array([[[1.76474623e-06, 1.76474623e-06, 1.76474623e-06, ...,
         1.76474623e-06, 1.76474623e-06, 1.76474623e-06],
        [2.57214128e-06, 2.96641565e-06, 2.85621081e-06, ...,
         2.66091843e-06, 2.73207093e-06, 2.86534919e-06],
        [5.19970808e-06, 4.18709442e-06, 4.08393544e-06, ...,
         4.72062948e-06, 4.84107477e-06, 5.10710470e-06],
        ...,
        [5.22522487e-06, 5.23916879e-06, 5.25457472e-06, ...,
         5.17782064e-06, 5.21256607e-06, 5.22326081e-06],
        [5.34919673e-06, 5.32315426e-06, 5.33667662e-06, ...,
         5.29863701e-06, 5.30857960e-06, 5.30882244e-06],
        [5.33703223e-06, 5.33703223e-06, 5.33703223e-06, ...,
         5.33703223e-06, 5.33703223e-06, 5.33703223e-06]],

       [[1.11591032e-06, 1.11591032e-06, 1.11591032e-06, ...,
         1.11591032e-06, 1.11591032e-06, 1.11591032e-06],
        [6.92375409e-07, 6.76795253e-07, 6.88448267e-07, ...,
         6.80786798e-07, 6.80518781e-07, 6.78294668e-07],
        [6.25709220e-07, 6.20482297e-07, 6.23010749e-07, ...,
         6.29511590e-07, 6.25784025e-07, 6.25872019e-07],
...
         4.50601510e-06, 4.51574397e-06, 4.52808627e-06],
        [4.40805343e-06, 4.43657837e-06, 4.41192287e-06, ...,
         4.51558981e-06, 4.49316076e-06, 4.47144112e-06],
        [3.98442990e-06, 3.98442990e-06, 3.98442990e-06, ...,
         3.98442990e-06, 3.98442990e-06, 3.98442990e-06]],

       [[3.70747148e-06, 3.70747148e-06, 3.70747148e-06, ...,
         3.70747148e-06, 3.70747148e-06, 3.70747148e-06],
        [4.69838005e-06, 5.02726516e-06, 5.35329673e-06, ...,
         5.52705706e-06, 5.37407914e-06, 5.07353252e-06],
        [5.32267086e-06, 5.69726217e-06, 5.90127274e-06, ...,
         5.36975904e-06, 5.35104937e-06, 5.30774560e-06],
        ...,
        [4.77814092e-06, 5.08615904e-06, 5.24006236e-06, ...,
         4.44501666e-06, 4.59308239e-06, 4.75009438e-06],
        [4.11456722e-06, 4.36241771e-06, 4.41689917e-06, ...,
         4.12225836e-06, 4.18115178e-06, 4.24182781e-06],
        [3.14402905e-06, 3.14402905e-06, 3.14402905e-06, ...,
         3.14402905e-06, 3.14402905e-06, 3.14402905e-06]]],
      shape=(1980, 192, 288), dtype=float32)
Coordinates:
  * time     (time) datetime64[ns] 16kB 1850-01-16T12:00:00 ... 2014-12-16T12...
  * lat      (lat) float64 2kB -90.0 -89.06 -88.12 -87.17 ... 88.12 89.06 90.0
  * lon      (lon) float64 2kB 0.0 1.25 2.5 3.75 5.0 ... 355.0 356.2 357.5 358.8
Attributes:
    regrid_method:  bilinear

In [16]:
clt_model1_mean = clt_model1rg.sel(time=slice("1950-01-01", "1980-12-31")).groupby("time.month").mean("time")
clt_model2_mean = clt_model2rg.sel(time=slice("1950-01-01", "1980-12-31")).groupby("time.month").mean("time")
clt_model3_mean = clt_model3.sel(time=slice("1950-01-01", "1980-12-31"))["clt"].groupby("time.month").mean("time")
clt_model4_mean = clt_model4.sel(time=slice("1950-01-01", "1980-12-31"))["clt"].groupby("time.month").mean("time")
clt_model5_mean = clt_model5.sel(time=slice("1950-01-01", "1980-12-31"))["clt"].groupby("time.month").mean("time")
clt_model6_mean = clt_model6rg.sel(time=slice("1950-01-01", "1980-12-31")).groupby("time.month").mean("time")
clt_model7_mean = clt_model7.sel(time=slice("1950-01-01", "1980-12-31"))["clt"].groupby("time.month").mean("time")

In [17]:
clt_model3_mean

<xarray.DataArray 'clt' (month: 12, lat: 192, lon: 288)> Size: 3MB
array([[[73.41167 , 73.41166 , 73.41165 , ..., 73.411644, 73.41167 ,
         73.411644],
        [69.170006, 69.1553  , 69.15957 , ..., 69.20637 , 69.20936 ,
         69.21547 ],
        [66.79935 , 66.723114, 66.71926 , ..., 66.87967 , 66.9004  ,
         66.866455],
        ...,
        [93.5121  , 93.52318 , 93.551926, ..., 93.57602 , 93.57219 ,
         93.52119 ],
        [93.356575, 93.385086, 93.41131 , ..., 93.355125, 93.3389  ,
         93.35705 ],
        [93.52743 , 93.527504, 93.52758 , ..., 93.528244, 93.52733 ,
         93.52734 ]],

       [[80.9864  , 80.9864  , 80.9864  , ..., 80.98639 , 80.9864  ,
         80.98639 ],
        [75.03262 , 75.01598 , 75.00732 , ..., 75.047195, 75.0491  ,
         75.053185],
        [72.57562 , 72.5519  , 72.52565 , ..., 72.58969 , 72.578285,
         72.57907 ],
...
        [94.166794, 94.14551 , 94.1301  , ..., 94.147606, 94.1575  ,
         94.15079 ],
        [94.31478 , 94.30713 , 94.336685, ..., 94.330475, 94.33915 ,
         94.33706 ],
        [94.25184 , 94.25231 , 94.25243 , ..., 94.25267 , 94.25263 ,
         94.25185 ]],

       [[70.65097 , 70.65097 , 70.65097 , ..., 70.651024, 70.65099 ,
         70.650986],
        [66.63268 , 66.61921 , 66.629715, ..., 66.67559 , 66.66746 ,
         66.66055 ],
        [64.30743 , 64.29715 , 64.29394 , ..., 64.35515 , 64.326805,
         64.34901 ],
        ...,
        [93.38011 , 93.42774 , 93.436455, ..., 93.23777 , 93.261696,
         93.295105],
        [93.557846, 93.59039 , 93.626076, ..., 93.44132 , 93.45776 ,
         93.50969 ],
        [93.51122 , 93.51136 , 93.51091 , ..., 93.509125, 93.5102  ,
         93.51023 ]]], shape=(12, 192, 288), dtype=float32)
Coordinates:
  * month    (month) int64 96B 1 2 3 4 5 6 7 8 9 10 11 12
  * lat      (lat) float64 2kB -90.0 -89.06 -88.12 -87.17 ... 88.12 89.06 90.0
  * lon      (lon) float64 2kB 0.0 1.25 2.5 3.75 5.0 ... 355.0 356.2 357.5 358.8
Attributes: (12/19)
    cell_measures:  area: areacella
    cell_methods:   area: time: mean
    comment:        for the whole atmospheric column, as seen from the surfac...
    description:    for the whole atmospheric column, as seen from the surfac...
    frequency:      mon
    id:             clt
    ...             ...
    time_label:     time-mean
    time_title:     Temporal mean
    title:          Total Cloud Cover Percentage
    type:           real
    units:          %
    variable_id:    clt

In [18]:
pr_model1_mean = pr_model1rg.sel(time=slice("1950-01-01", "1980-12-31")).groupby("time.month").mean("time")
pr_model2_mean = pr_model2rg.sel(time=slice("1950-01-01", "1980-12-31")).groupby("time.month").mean("time")
pr_model3_mean = pr_model3.sel(time=slice("1950-01-01", "1980-12-31"))["pr"].groupby("time.month").mean("time")
pr_model4_mean = pr_model4.sel(time=slice("1950-01-01", "1980-12-31"))["pr"].groupby("time.month").mean("time")
pr_model5_mean = pr_model5.sel(time=slice("1950-01-01", "1980-12-31"))["pr"].groupby("time.month").mean("time")
pr_model6_mean = pr_model6rg.sel(time=slice("1950-01-01", "1980-12-31")).groupby("time.month").mean("time")
pr_model7_mean = pr_model7.sel(time=slice("1950-01-01", "1980-12-31"))["pr"].groupby("time.month").mean("time")

In [19]:
clt_ensemble_mean = (clt_model1_mean.values+clt_model2_mean.values+clt_model3_mean.values+clt_model4_mean.values+clt_model5_mean.values+clt_model6_mean.values+clt_model7_mean.values)/7
pr_ensemble_mean = (pr_model1_mean.values+pr_model2_mean.values+pr_model3_mean.values+pr_model4_mean.values+pr_model5_mean.values+pr_model6_mean.values+pr_model7_mean.values)/7


In [21]:

df = pd.DataFrame({
    'clt_ensemble_mean': clt_ensemble_mean.flatten(),
    'pr_ensemble_mean': pr_ensemble_mean.flatten()
})

In [22]:
df.to_csv('resultados_pca.csv', index=False)
