In [23]:
import xarray as xr
import netCDF4
import numpy as np
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature
import pandas as pd
import numpy as np


In [51]:
#Abro los 7 datasets
clt_model1 = xr.open_dataset(r"..\modelos\clt\clt_Amon_ACCESS-CM2_historical_r1i1p1f1_gn_185001-201412.nc")
clt_model2 = xr.open_dataset(r"..\modelos\clt\clt_Amon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_185001-201412.nc")
clt_model3 = xr.open_dataset(r"..\modelos\clt\clt_Amon_CESM2-WACCM_historical_r1i1p1f1_gn_185001-201412.nc")
clt_model4 = xr.open_dataset(r"..\modelos\clt\clt_Amon_CMCC-CM2-SR5_historical_r1i1p1f1_gn_185001-201412.nc")
clt_model5 = xr.open_dataset(r"..\modelos\clt\clt_Amon_FIO-ESM-2-0_historical_r1i1p1f1_gn_185001-201412.nc")
clt_model6 = xr.open_dataset(r"..\modelos\clt\clt_Amon_MRI-ESM2-0_historical_r1i1p1f1_gn_185001-201412.nc")
clt_model7 = xr.open_dataset(r"..\modelos\clt\clt_Amon_TaiESM1_historical_r1i1p1f1_gn_185001-201412.nc")

c:\Users\clara\AppData\Local\Programs\Python\Python313\Lib\site-packages\xarray\conventions.py:204: SerializationWarning: variable 'clt' has multiple fill values {np.float32(1e+20), np.float64(1e+20)} defined, decoding all values to NaN.
  var = coder.decode(var, name=name)


In [52]:
pr_model1 = xr.open_dataset(r"..\modelos\pr\pr_Amon_ACCESS-CM2_historical_r1i1p1f1_gn_185001-201412.nc")
pr_model2 = xr.open_dataset(r"..\modelos\pr\pr_Amon_ACCESS-ESM1-5_historical_r1i1p1f1_gn_185001-201412.nc")
pr_model3 = xr.open_dataset(r"..\modelos/pr/pr_Amon_CESM2-WACCM_historical_r1i1p1f1_gn_185001-201412.nc")
pr_model4 = xr.open_dataset(r"..\modelos\pr\pr_Amon_CMCC-CM2-SR5_historical_r1i1p1f1_gn_185001-201412.nc")
pr_model5 = xr.open_dataset(r"..\modelos\pr\pr_Amon_FIO-ESM-2-0_historical_r1i1p1f1_gn_185001-201412.nc")
pr_model6 = xr.open_dataset(r"..\modelos\pr\pr_Amon_MRI-ESM2-0_historical_r1i1p1f1_gn_185001-201412.nc")
pr_model7 = xr.open_dataset(r"..\modelos\pr\pr_Amon_TaiESM1_historical_r1i1p1f1_gn_185001-201412.nc")

c:\Users\clara\AppData\Local\Programs\Python\Python313\Lib\site-packages\xarray\conventions.py:204: SerializationWarning: variable 'pr' has multiple fill values {np.float32(1e+20), np.float64(1e+20)} defined, decoding all values to NaN.
  var = coder.decode(var, name=name)


In [59]:
print(clt_model1.head())

<xarray.Dataset> Size: 860B
Dimensions:    (time: 5, bnds: 2, lat: 5, lon: 5)
Coordinates:
  * time       (time) datetime64[ns] 40B 1850-01-16T12:00:00 ... 1850-05-16T1...
  * lat        (lat) float64 40B -89.38 -88.12 -86.88 -85.62 -84.38
  * lon        (lon) float64 40B 0.9375 2.812 4.688 6.562 8.438
Dimensions without coordinates: bnds
Data variables:
    time_bnds  (time, bnds) datetime64[ns] 80B ...
    lat_bnds   (lat, bnds) float64 80B ...
    lon_bnds   (lon, bnds) float64 80B ...
    clt        (time, lat, lon) float32 500B ...
Attributes: (12/47)
    Conventions:            CF-1.7 CMIP-6.2
    activity_id:            CMIP
    branch_method:          standard
    branch_time_in_child:   0.0
    branch_time_in_parent:  0.0
    creation_date:          2019-11-08T10:46:33Z
    ...                     ...
    variable_id:            clt
    variant_label:          r1i1p1f1
    version:                v20191108
    cmor_version:           3.4.0
    tracking_id:            hdl:21.14

In [95]:
clt_model1rg = clt_model1["clt"].interp(lat=clt_model3.lat,lon=clt_model3.lon,method="linear")
# clt_model2rg = clt_model2["clt"].interp_like(clt_model3["clt"])
# clt_model6rg = clt_model6["clt"].interp_like(clt_model3["clt"])


In [97]:
clt_model1rg

<xarray.DataArray 'clt' (time: 1980, lat: 192, lon: 288)> Size: 876MB
array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan, 90.71865381, 90.79755214, ..., 90.34327961,
         90.43449415, 90.3188043 ],
        [        nan, 92.12282191, 91.5431477 , ..., 91.88520022,
         91.95965406, 92.08944697],
        ...,
        [        nan, 98.39287137, 98.25570737, ..., 98.56108021,
         98.52988358, 98.40787718],
        [        nan, 97.78886299, 97.75676894, ..., 97.98353105,
         98.02435431, 97.95996381],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan]],

       [[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan, 84.21485461, 84.51804915, ..., 84.14619006,
         84.42603839, 84.43973668],
        [        nan, 74.34586131, 74.27865872, ..., 73.25776584,
         73.12755219, 73.04416943],
...
        [        nan, 97.76911977, 97.83566194, ..., 97.56240445,
         97.62431306, 97.59224031],
        [        nan, 98.05861335, 98.16014688, ..., 97.98440983,
         97.97284457, 98.12851085],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan]],

       [[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan, 85.8703347 , 85.46298628, ..., 85.73566057,
         85.54561275, 85.69605962],
        [        nan, 87.7711564 , 87.28433446, ..., 88.07991387,
         87.58715884, 87.33617972],
        ...,
        [        nan, 93.17518038, 93.61960792, ..., 93.46491629,
         93.61692099, 93.63948163],
        [        nan, 96.30670731, 96.38393329, ..., 96.53996173,
         96.64473609, 96.38682261],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan]]], shape=(1980, 192, 288))
Coordinates:
  * time     (time) datetime64[ns] 16kB 1850-01-16T12:00:00 ... 2014-12-16T12...
  * lat      (lat) float64 2kB -90.0 -89.06 -88.12 -87.17 ... 88.12 89.06 90.0
  * lon      (lon) float64 2kB 0.0 1.25 2.5 3.75 5.0 ... 355.0 356.2 357.5 358.8
Attributes:
    standard_name:   cloud_area_fraction
    long_name:       Total Cloud Cover Percentage
    comment:         Total cloud area fraction (reported as a percentage) for...
    units:           %
    original_units:  1
    history:         2019-11-08T10:46:31Z altered by CMOR: Converted units fr...
    cell_methods:    area: time: mean
    cell_measures:   area: areacella

In [ ]:
pr_model1rg = pr_model1["pr"].interp_like(pr_model3["pr"])
pr_model2rg = pr_model2["pr"].interp_like(pr_model3["pr"])
pr_model6rg = pr_model6["pr"].interp_like(pr_model3["pr"])

In [50]:
clt_model1

<xarray.DataArray 'clt' (time: 1980, lat: 192, lon: 288)> Size: 876MB
array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
...
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]], shape=(1980, 192, 288))
Coordinates:
  * time     (time) object 16kB 1850-01-15 12:00:00 ... 2014-12-15 12:00:00
  * lat      (lat) float64 2kB -90.0 -89.06 -88.12 -87.17 ... 88.12 89.06 90.0
  * lon      (lon) float64 2kB 0.0 1.25 2.5 3.75 5.0 ... 355.0 356.2 357.5 358.8
Attributes:
    standard_name:   cloud_area_fraction
    long_name:       Total Cloud Cover Percentage
    comment:         Total cloud area fraction (reported as a percentage) for...
    units:           %
    original_units:  1
    history:         2019-11-08T10:46:31Z altered by CMOR: Converted units fr...
    cell_methods:    area: time: mean
    cell_measures:   area: areacella

In [64]:
clt_model1_mean = clt_model1rg.sel(time=slice("1950-01-01", "1980-12-31")).groupby("time.month").mean("time")
clt_model2_mean = clt_model2rg.sel(time=slice("1950-01-01", "1980-12-31")).groupby("time.month").mean("time")
clt_model3_mean = clt_model3.sel(time=slice("1950-01-01", "1980-12-31"))["clt"].groupby("time.month").mean("time")
clt_model4_mean = clt_model4.sel(time=slice("1950-01-01", "1980-12-31"))["clt"].groupby("time.month").mean("time")
clt_model5_mean = clt_model5.sel(time=slice("1950-01-01", "1980-12-31"))["clt"].groupby("time.month").mean("time")
clt_model6_mean = clt_model6rg.sel(time=slice("1950-01-01", "1980-12-31")).groupby("time.month").mean("time")
clt_model7_mean = clt_model7.sel(time=slice("1950-01-01", "1980-12-31"))["clt"].groupby("time.month").mean("time")

In [66]:
clt_model3_mean

<xarray.DataArray 'clt' (month: 12, lat: 192, lon: 288)> Size: 3MB
array([[[73.41167 , 73.41166 , 73.41165 , ..., 73.411644, 73.41167 ,
         73.411644],
        [69.170006, 69.1553  , 69.15957 , ..., 69.20637 , 69.20936 ,
         69.21547 ],
        [66.79935 , 66.723114, 66.71926 , ..., 66.87967 , 66.9004  ,
         66.866455],
        ...,
        [93.5121  , 93.52318 , 93.551926, ..., 93.57602 , 93.57219 ,
         93.52119 ],
        [93.356575, 93.385086, 93.41131 , ..., 93.355125, 93.3389  ,
         93.35705 ],
        [93.52743 , 93.527504, 93.52758 , ..., 93.528244, 93.52733 ,
         93.52734 ]],

       [[80.9864  , 80.9864  , 80.9864  , ..., 80.98639 , 80.9864  ,
         80.98639 ],
        [75.03262 , 75.01598 , 75.00732 , ..., 75.047195, 75.0491  ,
         75.053185],
        [72.57562 , 72.5519  , 72.52565 , ..., 72.58969 , 72.578285,
         72.57907 ],
...
        [94.166794, 94.14551 , 94.1301  , ..., 94.147606, 94.1575  ,
         94.15079 ],
        [94.31478 , 94.30713 , 94.336685, ..., 94.330475, 94.33915 ,
         94.33706 ],
        [94.25184 , 94.25231 , 94.25243 , ..., 94.25267 , 94.25263 ,
         94.25185 ]],

       [[70.65097 , 70.65097 , 70.65097 , ..., 70.651024, 70.65099 ,
         70.650986],
        [66.63268 , 66.61921 , 66.629715, ..., 66.67559 , 66.66746 ,
         66.66055 ],
        [64.30743 , 64.29715 , 64.29394 , ..., 64.35515 , 64.326805,
         64.34901 ],
        ...,
        [93.38011 , 93.42774 , 93.436455, ..., 93.23777 , 93.261696,
         93.295105],
        [93.557846, 93.59039 , 93.626076, ..., 93.44132 , 93.45776 ,
         93.50969 ],
        [93.51122 , 93.51136 , 93.51091 , ..., 93.509125, 93.5102  ,
         93.51023 ]]], shape=(12, 192, 288), dtype=float32)
Coordinates:
  * lat      (lat) float64 2kB -90.0 -89.06 -88.12 -87.17 ... 88.12 89.06 90.0
  * lon      (lon) float64 2kB 0.0 1.25 2.5 3.75 5.0 ... 355.0 356.2 357.5 358.8
  * month    (month) int64 96B 1 2 3 4 5 6 7 8 9 10 11 12
Attributes: (12/19)
    cell_measures:  area: areacella
    cell_methods:   area: time: mean
    comment:        for the whole atmospheric column, as seen from the surfac...
    description:    for the whole atmospheric column, as seen from the surfac...
    frequency:      mon
    id:             clt
    ...             ...
    time_label:     time-mean
    time_title:     Temporal mean
    title:          Total Cloud Cover Percentage
    type:           real
    units:          %
    variable_id:    clt

In [ ]:
pr_model1_mean = pr_model1rg.sel(time=slice("1950-01-01", "1980-12-31")).groupby("time.month").mean("time")
pr_model2_mean = pr_model2rg.sel(time=slice("1950-01-01", "1980-12-31")).groupby("time.month").mean("time")
pr_model3_mean = pr_model3.sel(time=slice("1950-01-01", "1980-12-31"))["pr"].groupby("time.month").mean("time")
pr_model4_mean = pr_model4.sel(time=slice("1950-01-01", "1980-12-31"))["pr"].groupby("time.month").mean("time")
pr_model5_mean = pr_model5.sel(time=slice("1950-01-01", "1980-12-31"))["pr"].groupby("time.month").mean("time")
pr_model6_mean = pr_model6rg.sel(time=slice("1950-01-01", "1980-12-31")).groupby("time.month").mean("time")
pr_model7_mean = pr_model7.sel(time=slice("1950-01-01", "1980-12-31"))["pr"].groupby("time.month").mean("time")

In [44]:
clt_ensemble_mean = (clt_model1_mean.values+clt_model2_mean.values+clt_model3_mean.values+clt_model4_mean.values+clt_model5_mean.values+clt_model6_mean.values+clt_model7_mean.values)/7
pr_ensemble_mean = (pr_model1_mean.values+pr_model2_mean.values+pr_model3_mean.values+pr_model4_mean.values+pr_model5_mean.values+pr_model6_mean.values+pr_model7_mean.values)/7


In [49]:
clt_model1_mean

<xarray.DataArray 'clt' (month: 12, lat: 192, lon: 288)> Size: 5MB
array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
...
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]], shape=(12, 192, 288))
Coordinates:
  * lat      (lat) float64 2kB -90.0 -89.06 -88.12 -87.17 ... 88.12 89.06 90.0
  * lon      (lon) float64 2kB 0.0 1.25 2.5 3.75 5.0 ... 355.0 356.2 357.5 358.8
  * month    (month) int64 96B 1 2 3 4 5 6 7 8 9 10 11 12
Attributes:
    standard_name:   cloud_area_fraction
    long_name:       Total Cloud Cover Percentage
    comment:         Total cloud area fraction (reported as a percentage) for...
    units:           %
    original_units:  1
    history:         2019-11-08T10:46:31Z altered by CMOR: Converted units fr...
    cell_methods:    area: time: mean
    cell_measures:   area: areacella

In [ ]:
clt_ensemble_mean = clt_ensemble_mean.values
pr_ensemble_mean = pr_ensemble_mean.values

df = pd.DataFrame({
    'clt_ensemble_mean': clt_ensemble_mean.flatten(),
    'pr_ensemble_mean': pr_ensemble_mean.flatten()
})

In [11]:
df.to_csv('resultados_pca.csv', index=False)
